specify_custom_cache_location
aurora-is-near/rainbow-bridge pull request #674
Opened 2022-01-05 02:38 UTC by rigidus

2022-02-18 13:34 UTC, sept-en commented on eth2near/ethashproof/cmd/cache/main.go
> +	// fmt.Printf("CacheDir: %s\n", cacheDir)
Commented out code should be removed.

```suggestion
```

2022-02-18 13:40 UTC, sept-en commented on eth2near/ethashproof/cmd/cache/main.go
> +		cacheDir = getCacheDir(cacheDirIdx)
```suggestion
	argsCount := len(os.Args)
	epochArgIdx := 1
	cacheDirArgIdx := 2
        var epoch int
	var cacheDir string

	switch argsCount {
	case 1:
		usage("Error: Epoch number param is missing\n")
	case 2:
		epoch = getEpoch(epochArgIdx)
		cacheDir = "|default|"
	case 3:
		epoch = getEpoch(epochArgIdx)
		cacheDir = getCacheDir(cacheDirArgIdx)
```

2022-02-18 14:19 UTC, karim-en requested changes

2022-02-18 14:19 UTC, karim-en commented on eth2near/ethashproof/dag_merkle_root.go
> +	if cacheDir == "|default|" {
Please don't use string literal as an option, you can just check for empty string here.

2022-11-09 23:49 UTC, sept-en requested changes
Closed as a stalled. Any new changes should take into account the existence of eth2-to-near-relay and eth2-client.

2022-11-09 23:49 UTC, closed without merging