Eth client: improve init and add tests
aurora-is-near/rainbow-bridge pull request #768
Opened 2022-07-31 22:18 UTC by karim-en

Fix #765 and add additional unit tests for it

2022-07-31 23:14 UTC, sept-en commented
@karim-en please rebase on top of `the-merge` branch

2022-07-31 23:30 UTC, sept-en requested changes

2022-07-31 23:30 UTC, sept-en commented on contracts/near/eth2-client/src/lib.rs
> +                "The client can't be executed in (trustless mode) and (without bls) on mainnet."
```suggestion
                "The client can't be executed in the trustless mode without BLS sigs verification on Mainnet"
```

2022-07-31 23:30 UTC, sept-en commented on contracts/near/eth2-client/src/tests/unit_tests.rs
> +        expected = "The client can't be executed in (trustless mode) and (without bls) on mainnet."
```suggestion
        expected = "The client can't be executed in the trustless mode without BLS sigs verification on Mainnet"
```

2022-07-31 23:30 UTC, sept-en commented on contracts/near/eth2-client/src/tests/unit_tests.rs
> +        expected = "The client can't be executed in (trustless mode) and (without bls) on mainnet."
```suggestion
        expected = "The client can't be executed in the trustless mode without BLS sigs verification on Mainnet"
```

2022-07-31 23:30 UTC, sept-en commented on contracts/near/eth2-client/src/tests/unit_tests.rs
> +    pub fn test_panic_on_init_in_trusted_mode_without_bls_on_mainnet() {
I belive it's a typo
```suggestion
    )]
    pub fn test_panic_on_init_in_trustless_mode_without_bls_on_mainnet() {
```

2022-07-31 23:30 UTC, sept-en commented on contracts/near/eth2-client/src/tests/unit_tests.rs
> +    pub fn test_panic_on_init_in_trusted_mode_without_bls_feature_flag() {
I believe it's a typo
```suggestion
    pub fn test_panic_on_init_in_trustless_mode_without_bls_feature_flag() {
```

2022-08-01 00:24 UTC, merged

2022-08-01 09:02 UTC, olga24912 reviewed
OK