Eth2-to-Near Relay: rid of `LightClientServer API` for fetching next_sync_committee in HandMadeLightClientUpdate
aurora-is-near/rainbow-bridge pull request #783
Opened 2022-08-09 15:38 UTC by olga24912

2022-08-09 17:04 UTC, karim-en approved these changes

2022-08-10 04:28 UTC, sept-en commented
@olga24912 please rebase on top of `the-merge` branch

2022-08-16 22:52 UTC, sept-en requested changes

2022-08-16 22:52 UTC, sept-en commented on eth2near/eth2near-block-relay-rs/src/hand_made_finality_light_client_update.rs
> +                    .collect(),
```suggestion
                next_sync_committee
                    .pubkeys
                    .iter()
                    .copied()
                    .map(|x| eth_types::eth2::PublicKeyBytes(x.serialize()))
                    .collect(),
```

2022-08-16 22:52 UTC, sept-en commented on eth2near/eth2near-block-relay-rs/src/hand_made_finality_light_client_update.rs
> +                    .as_u64(), &beacon_rpc_client)?),
Wrong formatting + redundant borrow

```suggestion
                true => Some(Self::get_next_sync_committee(
                    finality_header.slot.as_u64(),
                    beacon_rpc_client,
                )?),
```

2022-08-16 22:53 UTC, sept-en approved these changes

2022-08-16 23:03 UTC, merged