Eth2Near-relay: fix the contract initialization
aurora-is-near/rainbow-bridge pull request #841
Opened 2022-10-25 10:15 UTC by olga24912

* Get the light client update for last finality slot instead the some slot in current period during initialization
* Add workspace for eth2near relay

2022-10-26 01:00 UTC, sept-en requested changes
Added initial review. Please also check, one of the relayer tests is failing.

2022-11-02 16:53 UTC, olga24912 commented on eth2near/Cargo.toml
> +eth2_serde_utils = { git = "https://github.com/aurora-is-near/lighthouse.git", rev = "b624c3f0d3c5bc9ea46faa14c9cb2d90ee1e1dec" }
fixed https://github.com/aurora-is-near/rainbow-bridge/pull/841/commits/3ed8c2c4ca483f559a2839ed861fd3f681a3d648

2022-11-02 16:53 UTC, olga24912 commented on eth2near/eth2-contract-init/src/init_contract.rs
> +
fixed https://github.com/aurora-is-near/rainbow-bridge/pull/841/commits/74ef2b0b9ff7c65b39c34dcb5abd04b52f618b34

2022-11-04 16:29 UTC, karim-en approved these changes

2022-11-05 01:20 UTC, sept-en approved these changes

2022-11-05 01:21 UTC, merged