Shapella upgrade
aurora-is-near/rainbow-bridge pull request #878
Opened 2023-03-16 01:38 UTC by karim-en

2023-03-24 19:57 UTC, sept-en requested changes

2023-03-24 19:57 UTC, sept-en commented on contracts/near/Cargo.toml
> +eth2_ssz_derive = { git = "https://github.com/aurora-is-near/lighthouse.git",  rev = "ec55f0b8eb997c80364f01afef74114ce139bcae" }
Please use a tag instead.

2023-03-24 19:57 UTC, sept-en commented on contracts/near/eth-client/Cargo.toml
> +ethash = { git = "https://github.com/aurora-is-near/rust-ethash", rev = "a27b2c7217f74c4470d7cd0b26b41b58431a26ee", default-features = false }
Please use a tag instead.

2023-03-27 11:53 UTC, olga24912 approved these changes

2023-03-27 20:29 UTC, karim-en commented on contracts/near/Cargo.toml
> +eth2_ssz_derive = { git = "https://github.com/aurora-is-near/lighthouse.git",  rev = "ec55f0b8eb997c80364f01afef74114ce139bcae" }
Fixed 3a57c023e2ff75b75f5fbeb2c1c97c15531a5fd7

2023-03-27 20:47 UTC, karim-en commented on contracts/near/eth-client/Cargo.toml
> +ethash = { git = "https://github.com/aurora-is-near/rust-ethash", rev = "a27b2c7217f74c4470d7cd0b26b41b58431a26ee", default-features = false }
Fixed 7ff9642f1500a3cd69babe8a9a44fb6760933634

2023-03-28 02:00 UTC, sept-en requested changes

2023-03-28 17:26 UTC, sept-en approved these changes

2023-03-28 17:28 UTC, merged