Fix `GasLimitExceeded` error
aurora-is-near/rainbow-bridge pull request #896
Opened 2023-05-05 18:58 UTC by karim-en

The hash function `near_sdk::env::keccak256` randomly panics `HostError(GasLimitExceeded)` when calling it not in a near contract.

2023-06-02 16:24 UTC, olga24912 approved these changes

2023-06-05 12:05 UTC, UrAvgDeveloper reviewed
Why can't we use `sha3` package only for both scenarios?

2023-06-05 21:08 UTC, sept-en requested changes

2023-06-06 15:00 UTC, sept-en approved these changes

2023-06-06 15:01 UTC, merged